<?php

$quotes = array(
	array("Al Capone","Capitalism is the legitimate racket of the ruling class."),
	array("Al Capone","I am like any other man. All I do is supply a demand."),
	array("Al Capone","I don't even know what street Canada is on."),
	array("Al Capone","I have built my organization upon fear."),
	array("Al Capone","My rackets are run on strictly American lines and they're going to stay that way."),
	array("Al Capone","Now I know why tigers eat their young."),
	array("Al Capone","Prohibition has made nothing but trouble."),
	array("Al Capone","This American system of ours, call it Americanism, call it capitalism, call it what you will, gives each and every one of us a great opportunity if we only seize it with both hands and make the most of it."),
	array("Al Capone","Vote early and vote often."),
	array("Al Capone","When I sell liquor, it's called bootlegging; when my patrons serve it on Lake Shore Drive, it's called hospitality."),
	array("Al Capone","You can get much farther with a kind word and a gun than you can with a kind word alone."),
	array("Nice Guy Eddie", "Okay, first things fuckin' last!"),
	array("Nice Guy Eddie", "We got places all over the place."),
	array("Mr. White", "Smoke? "),
	array("Mr. Brown", "Let me tell you what 'Like a Virgin' is about. It's all about a girl who digs a guy with a big dick. The entire song. It's a metaphor for big dicks. "),
	array("Mr. Brown", "Hey, you guys are making me lose my... train of thought here. I was saying something, what was it? "),
	array("Mr. Brown", "What the fuck was I talking about? "),
	array("Joe", "He was the only one I wasn't 100% on. I should have my fuckin' head examined, going on a plan like this when I wasn't 100%. "),
	array("Joe", "You don't need proof when you have instinct."),
	array("Mr. Blonde", "Was that as good for you as it was for me?"),
	array("Nice Guy Eddie", "Okay, Mr. Fucking Detective! You're so fucking smart. Who did it? Who set us up? "),
	array("Mr. Pink", "What the fuck d'ya think we've been askin' each other? "),
	array("Nice Guy Eddie", "I don't even know a fucking Jew who'd have the balls to say that. Let me get this straight: you don't ever tip? "),
	array("Mr. Blonde", "Torture you? That's a good idea. I like that."),
	array("Mr. White", "Hardy fuckin' har."),
	array("Mr. Pink", "Somebody's shoved a red-hot poker up our ass, and I want to know whose name is on the handle!"),
	array("Mr. Blonde", "Are you gonna bark all day, little doggy, or are you gonna bite? "),
	array("Mr. Blonde", "Hey Joe, you want me to shoot this guy? "),
	array("Mr. Blonde", "Either he's alive or he's dead, or the cops got him... or they don't."),
	array("Joe", "Only one thing to do in that case: shit in yer pants an' dive in and swim!"),
	array("Mr. White", "Bam. Bam. Bam. Bam. "),
	array("Mr. Pink", "I don't wanna kill anybody. But if I gotta get out that door, and you're standing in my way, one way or the other, you're gettin' outta my way."),
	array("Mr. Pink", "This is bad. This is so fucking bad. Is it bad? "),
	array("Joe", "Cough up a buck you cheap bastard."),
	array("Mr. Pink", "Where's the commode in this dungeon? I gotta take a squirt."),
	array("Mr. Orange", "You're not blind, you've just got blood in your eyes."),
	array("Joe", "Hey! NOBODY'S trading with ANYBODY. This ain't a goddamn, fucking city council meeting, you know. Now listen up, Mr. Pink. There's two ways you can go on this job: my way or the highway. Now what's it gonna be, Mr. Pink?"),
	array("Tommy DeVito", "How am I meant to know you're kidding? What you mean, you're kidding? You breaking my fuckin' balls?"),
	array("Tommy DeVito", "Who the fuck cares? I'll dig the fuckin' hole. I don't give a fuck. What is it, the first hole I dug? Not the first time I dug a hole. I'll fuckin' dig a hole. Where are the shovels?"),
	array("Tommy DeVito", "Sure, mom, I settle down with a nice girl every night, then I'm free the next morning."),
	array("Tommy DeVito", " You mother fuck... Fuck! Keep that motherfucker here, keep him here! "),
	array("Tommy DeVito", 'He said, "No, you\'re gonna tell me something today, tough guy." I said, "All right, I\'ll tell you something: go fuck your mother."'),
	array("Tommy DeVito", "Oklahoma kid. That's me. I'm the Oklahoma kid. You fuckin' varmint! Dance. Dance. YAHOO, YA MOTHERFUCKER! "),
	array("Tommy DeVito", "You dizzy motherfucker, you!"),
	array("Tommy DeVito", "What the fuck you looking at? Come on. Make that coffee to go. Let's go. "),
	array("Tommy DeVito", "What am I, a mirage?"),
	array("Jimmy Conway", "Oh, hey, Henry, Henry! Here's an arm! "),
	)
?>